export const jyotirlingas = [
  { id:1,  name:"Somnath",         nameHi:"सोमनाथ",         state:"Gujarat",          stateHi:"गुजरात",          done:true,  emoji:"🌊" },
  { id:2,  name:"Mallikarjuna",    nameHi:"मल्लिकार्जुन",    state:"Andhra Pradesh",   stateHi:"आंध्र प्रदेश",    done:true,  emoji:"🌺" },
  { id:3,  name:"Mahakaleshwar",   nameHi:"महाकालेश्वर",     state:"Madhya Pradesh",   stateHi:"मध्य प्रदेश",     done:false, emoji:"🕉️" },
  { id:4,  name:"Omkareshwar",     nameHi:"ओंकारेश्वर",      state:"Madhya Pradesh",   stateHi:"मध्य प्रदेश",     done:false, emoji:"🏝️" },
  { id:5,  name:"Kedarnath",       nameHi:"केदारनाथ",        state:"Uttarakhand",      stateHi:"उत्तराखंड",       done:true,  emoji:"🏔️" },
  { id:6,  name:"Bhimashankar",    nameHi:"भीमाशंकर",        state:"Maharashtra",      stateHi:"महाराष्ट्र",      done:false, emoji:"🌿" },
  { id:7,  name:"Kashi Vishwanath",nameHi:"काशी विश्वनाथ",   state:"Uttar Pradesh",    stateHi:"उत्तर प्रदेश",    done:true,  emoji:"🏛️" },
  { id:8,  name:"Trimbakeshwar",   nameHi:"त्र्यंबकेश्वर",   state:"Maharashtra",      stateHi:"महाराष्ट्र",      done:false, emoji:"💧" },
  { id:9,  name:"Vaidyanath",      nameHi:"वैद्यनाथ",        state:"Jharkhand",        stateHi:"झारखंड",          done:false, emoji:"🌸" },
  { id:10, name:"Nageshwar",       nameHi:"नागेश्वर",        state:"Gujarat",          stateHi:"गुजरात",          done:false, emoji:"🐍" },
  { id:11, name:"Rameshwaram",     nameHi:"रामेश्वरम",       state:"Tamil Nadu",       stateHi:"तमिल नाडु",       done:false, emoji:"🌴" },
  { id:12, name:"Grishneshwar",    nameHi:"घृष्णेश्वर",      state:"Maharashtra",      stateHi:"महाराष्ट्र",      done:false, emoji:"🪨" },
];

export const charDham = [
  { id:1, name:"Kedarnath",  nameHi:"केदारनाथ",  state:"Uttarakhand", stateHi:"उत्तराखंड", done:true,  emoji:"🏔️" },
  { id:2, name:"Badrinath",  nameHi:"बद्रीनाथ",  state:"Uttarakhand", stateHi:"उत्तराखंड", done:false, emoji:"❄️" },
  { id:3, name:"Gangotri",   nameHi:"गंगोत्री",   state:"Uttarakhand", stateHi:"उत्तराखंड", done:false, emoji:"🌊" },
  { id:4, name:"Yamunotri",  nameHi:"यमुनोत्री",  state:"Uttarakhand", stateHi:"उत्तराखंड", done:false, emoji:"💦" },
];

export const visits = [
  { id:1, name:"Kedarnath Temple",         nameHi:"केदारनाथ मंदिर",         location:"Uttarakhand",      locationHi:"उत्तराखंड",       date:"May 2026",  dateHi:"मई 2026",      emoji:"🏔️", color:"#E1F5EE", done:true  },
  { id:2, name:"Dwarka — Dwarkadhish",     nameHi:"द्वारका — द्वारकाधीश",   location:"Gujarat",          locationHi:"गुजरात",           date:"Nov 2025",  dateHi:"नवंबर 2025",   emoji:"🌊", color:"#E6F1FB", done:true  },
  { id:3, name:"Srisailam — Mallikarjuna", nameHi:"श्रीशैलम — मल्लिकार्जुन", location:"Andhra Pradesh",   locationHi:"आंध्र प्रदेश",     date:"Jan 2026",  dateHi:"जनवरी 2026",   emoji:"🌺", color:"#FAECE7", done:true  },
  { id:4, name:"Udupi — Krishna Matha",    nameHi:"उडुपी — कृष्ण मठ",       location:"Karnataka",        locationHi:"कर्नाटक",          date:"Mar 2025",  dateHi:"मार्च 2025",   emoji:"🏛️", color:"#EEEDFE", done:true  },
  { id:5, name:"Somnath Temple",           nameHi:"सोमनाथ मंदिर",           location:"Gujarat",          locationHi:"गुजरात",           date:"Oct 2024",  dateHi:"अक्टूबर 2024", emoji:"🕌", color:"#E1F5EE", done:true  },
  { id:6, name:"Puri — Jagannath Temple",  nameHi:"पुरी — जगन्नाथ मंदिर",   location:"Odisha",           locationHi:"ओडिशा",            date:"Aug 2026",  dateHi:"अगस्त 2026",   emoji:"⭐", color:"#FAEEDA", done:false },
];

export const alerts = [
  { id:1, name:"Tirumala Venkateswara", nameHi:"तिरुमला वेंकटेश्वर", state:"Andhra Pradesh", stateHi:"आंध्र प्रदेश", desc:"SSD slots for Aug–Sep 2026", descHi:"अगस्त–सितंबर 2026 के लिए SSD स्लॉट", active:true,  type:"Darshan booking",    typeHi:"दर्शन बुकिंग"         },
  { id:2, name:"Kedarnath Temple",      nameHi:"केदारनाथ मंदिर",     state:"Uttarakhand",    stateHi:"उत्तराखंड",     desc:"2027 season opening & helicopter alerts", descHi:"2027 सीज़न खुलने व हेलिकॉप्टर की सूचना", active:true,  type:"Season opening",     typeHi:"मंदिर खुलने की सूचना" },
  { id:3, name:"Puri — Jagannath Rath Yatra", nameHi:"पुरी — जगन्नाथ रथ यात्रा", state:"Odisha", stateHi:"ओडिशा", desc:"Festival date & crowd advisory", descHi:"उत्सव तिथि और भीड़ की जानकारी", active:false, type:"Festival", typeHi:"उत्सव" },
];

export const recommendations = {
  jyoti: [
    { name:"Omkareshwar",    nameHi:"ओंकारेश्वर",    state:"Madhya Pradesh", stateHi:"मध्य प्रदेश" },
    { name:"Mahakaleshwar",  nameHi:"महाकालेश्वर",   state:"Madhya Pradesh", stateHi:"मध्य प्रदेश" },
    { name:"Trimbakeshwar",  nameHi:"त्र्यंबकेश्वर", state:"Maharashtra",    stateHi:"महाराष्ट्र"  },
  ],
  chardham: [
    { name:"Badrinath", nameHi:"बद्रीनाथ", state:"Uttarakhand", stateHi:"उत्तराखंड" },
    { name:"Gangotri",  nameHi:"गंगोत्री",  state:"Uttarakhand", stateHi:"उत्तराखंड" },
  ],
  shakti: [
    { name:"Kamakhya",    nameHi:"कामाख्या",    state:"Assam", stateHi:"असम"              },
    { name:"Vaishno Devi",nameHi:"वैष्णो देवी", state:"J&K",   stateHi:"जम्मू & कश्मीर" },
  ],
};

export const purohits = [
  { id:1, name:"Pt. Ramesh Sharma",  nameHi:"पं. रमेश शर्मा",  area:"Nawada, Bihar",  areaHi:"नवादा, बिहार",  speciality:"Vivah, Griha Pravesh, Satyanarayan Katha",   specialityHi:"विवाह, गृह प्रवेश, सत्यनारायण कथा",  experience:"22 yrs", experienceHi:"22 वर्ष", rating:4.9, reviews:84,  available:true,  phone:"+91 98765 43210", languages:["Hindi","Sanskrit"],           languagesHi:["हिंदी","संस्कृत"]              },
  { id:2, name:"Pt. Suresh Tiwari",  nameHi:"पं. सुरेश तिवारी", area:"Patna, Bihar",   areaHi:"पटना, बिहार",   speciality:"Navagraha Puja, Rudrabhishek, Kaal Sarp Dosh", specialityHi:"नवग्रह पूजा, रुद्राभिषेक, काल सर्प दोष", experience:"15 yrs", experienceHi:"15 वर्ष", rating:4.7, reviews:61,  available:true,  phone:"+91 91234 56789", languages:["Hindi","Sanskrit","Maithili"],  languagesHi:["हिंदी","संस्कृत","मैथिली"]    },
  { id:3, name:"Pt. Dinesh Mishra",  nameHi:"पं. दिनेश मिश्रा", area:"Gaya, Bihar",    areaHi:"गया, बिहार",    speciality:"Pitra Dosh, Pitru Paksha, Shraddha Karma",    specialityHi:"पितृ दोष, पितृ पक्ष, श्राद्ध कर्म",    experience:"30 yrs", experienceHi:"30 वर्ष", rating:5.0, reviews:132, available:false, phone:"+91 99887 76655", languages:["Hindi","Sanskrit","Bhojpuri"],  languagesHi:["हिंदी","संस्कृत","भोजपुरी"]   },
  { id:4, name:"Pt. Anil Pandey",    nameHi:"पं. अनिल पांडेय",  area:"Nawada, Bihar",  areaHi:"नवादा, बिहार",  speciality:"Mundan, Upanayana, Annaprashan",               specialityHi:"मुंडन, उपनयन, अन्नप्राशन",              experience:"18 yrs", experienceHi:"18 वर्ष", rating:4.8, reviews:47,  available:true,  phone:"+91 97654 32109", languages:["Hindi","Sanskrit"],           languagesHi:["हिंदी","संस्कृत"]              },
];

export const liveStreams = [
  { id:1, temple:"Kashi Vishwanath",       templeHi:"काशी विश्वनाथ",     location:"Varanasi, Uttar Pradesh",    locationHi:"वाराणसी, उत्तर प्रदेश",  youtubeId:"YyBcaGcvmzY", channelName:"Shri Kashi Vishwanath Temple", channelNameHi:"श्री काशी विश्वनाथ मंदिर", isLive:true,  viewers:"12.4K", emoji:"🏛️", color:"#FAECE7" },
  { id:2, temple:"Tirumala Venkateswara",  templeHi:"तिरुमला वेंकटेश्वर", location:"Tirupati, Andhra Pradesh",   locationHi:"तिरुपति, आंध्र प्रदेश",  youtubeId:"YyBcaGcvmzY", channelName:"TTD Official",                channelNameHi:"TTD आधिकारिक",             isLive:true,  viewers:"31.2K", emoji:"⛰️", color:"#E6F1FB" },
  { id:3, temple:"Shirdi Sai Baba",        templeHi:"शिरडी साईं बाबा",    location:"Shirdi, Maharashtra",        locationHi:"शिरडी, महाराष्ट्र",       youtubeId:"YyBcaGcvmzY", channelName:"Shri Sai Baba Sansthan",      channelNameHi:"श्री साईं बाबा संस्थान",  isLive:true,  viewers:"8.7K",  emoji:"🌺", color:"#E1F5EE" },
  { id:4, temple:"Kedarnath Temple",       templeHi:"केदारनाथ मंदिर",     location:"Uttarakhand",                locationHi:"उत्तराखंड",               youtubeId:"YyBcaGcvmzY", channelName:"Kedarnath Live",              channelNameHi:"केदारनाथ लाइव",            isLive:false, viewers:"—",     emoji:"🏔️", color:"#EEEDFE" },
  { id:5, temple:"Siddhivinayak Temple",   templeHi:"सिद्धिविनायक मंदिर", location:"Mumbai, Maharashtra",        locationHi:"मुंबई, महाराष्ट्र",       youtubeId:"YyBcaGcvmzY", channelName:"Siddhivinayak Official",      channelNameHi:"सिद्धिविनायक आधिकारिक",  isLive:true,  viewers:"5.1K",  emoji:"🐘", color:"#FAEEDA" },
  { id:6, temple:"Somnath Temple",         templeHi:"सोमनाथ मंदिर",       location:"Gujarat",                    locationHi:"गुजरात",                  youtubeId:"YyBcaGcvmzY", channelName:"Somnath Trust",               channelNameHi:"सोमनाथ ट्रस्ट",           isLive:false, viewers:"—",     emoji:"🌊", color:"#E1F5EE" },
];

// ── Temple Bookings — verified official URLs ──
export const templeBookings = [
  // 12 Jyotirlingas
  { id:1,  name:"Somnath Temple",           nameHi:"सोमनाथ मंदिर",           location:"Prabhas Patan, Gujarat",     locationHi:"प्रभास पाटन, गुजरात",   emoji:"🌊", color:"#E6F1FB", url:"https://somnath.org",                          services:["Darshan Slot","Light & Sound Show","Room Booking"], servicesHi:["दर्शन स्लॉट","लाइट शो","कमरा बुकिंग"],                    category:"Jyotirlinga", tag:"Official",   tagHi:"आधिकारिक",   tagBg:"#E1F5EE", tagColor:"#085041" },
  { id:2,  name:"Mallikarjuna — Srisailam", nameHi:"मल्लिकार्जुन — श्रीशैलम", location:"Kurnool, Andhra Pradesh",    locationHi:"कुर्नूल, आंध्र प्रदेश", emoji:"🌺", color:"#FAECE7", url:"https://srisailadevasthanam.org",              services:["Darshan Token","VIP Pass","Seva Booking"],          servicesHi:["दर्शन टोकन","VIP पास","सेवा बुकिंग"],                    category:"Jyotirlinga", tag:"Official",   tagHi:"आधिकारिक",   tagBg:"#E1F5EE", tagColor:"#085041" },
  { id:3,  name:"Mahakaleshwar",            nameHi:"महाकालेश्वर",             location:"Ujjain, Madhya Pradesh",     locationHi:"उज्जैन, मध्य प्रदेश",   emoji:"🕉️", color:"#EEEDFE", url:"https://mahakaleshwar.nic.in",                 services:["Bhasma Aarti","Darshan Pass","Puja Booking"],       servicesHi:["भस्म आरती","दर्शन पास","पूजा बुकिंग"],                   category:"Jyotirlinga", tag:"Official",   tagHi:"आधिकारिक",   tagBg:"#E1F5EE", tagColor:"#085041" },
  { id:4,  name:"Omkareshwar",              nameHi:"ओंकारेश्वर",              location:"Khandwa, Madhya Pradesh",    locationHi:"खंडवा, मध्य प्रदेश",    emoji:"🏝️", color:"#E1F5EE", url:"https://shriomkareshwar.org/OnlineTicketBooking.aspx", services:["Shighra Darshan","Wristband Booking"],             servicesHi:["शीघ्र दर्शन","रिस्टबैंड बुकिंग"],                       category:"Jyotirlinga", tag:"Official",   tagHi:"आधिकारिक",   tagBg:"#E1F5EE", tagColor:"#085041" },
  { id:5,  name:"Kedarnath Temple",         nameHi:"केदारनाथ मंदिर",          location:"Rudraprayag, Uttarakhand",   locationHi:"रुद्रप्रयाग, उत्तराखंड",emoji:"🏔️", color:"#EEEDFE", url:"https://badrinath-kedarnath.gov.in",           services:["Yatra Registration","Puja Booking","Helicopter"],   servicesHi:["यात्रा पंजीकरण","पूजा बुकिंग","हेलिकॉप्टर"],            category:"Jyotirlinga", tag:"Govt Portal",tagHi:"सरकारी",     tagBg:"#E6F1FB", tagColor:"#1A4A8A" },
  { id:6,  name:"Kashi Vishwanath",         nameHi:"काशी विश्वनाथ",           location:"Varanasi, Uttar Pradesh",    locationHi:"वाराणसी, उत्तर प्रदेश", emoji:"🏛️", color:"#FAECE7", url:"https://shrikashivishwanath.org",              services:["Darshan Pass","Puja Booking","VIP Entry"],          servicesHi:["दर्शन पास","पूजा बुकिंग","VIP प्रवेश"],                  category:"Jyotirlinga", tag:"Official",   tagHi:"आधिकारिक",   tagBg:"#E1F5EE", tagColor:"#085041" },
  { id:7,  name:"Trimbakeshwar",            nameHi:"त्र्यंबकेश्वर",           location:"Nashik, Maharashtra",        locationHi:"नासिक, महाराष्ट्र",     emoji:"💧", color:"#E6F1FB", url:"https://trimbakeshwartrust.com/onlinevip",     services:["VIP Darshan","Donation Pass"],                      servicesHi:["VIP दर्शन","दान पास"],                                    category:"Jyotirlinga", tag:"Official",   tagHi:"आधिकारिक",   tagBg:"#E1F5EE", tagColor:"#085041" },
  { id:8,  name:"Rameshwaram",              nameHi:"रामेश्वरम",               location:"Ramanathapuram, Tamil Nadu", locationHi:"रामनाथपुरम, तमिल नाडु", emoji:"🌴", color:"#E1F5EE", url:"https://www.rameswaramtemple.tnhrce.in",       services:["Darshan Ticket","Abhishekam","Puja Booking"],       servicesHi:["दर्शन टिकट","अभिषेकम","पूजा बुकिंग"],                    category:"Jyotirlinga", tag:"Official",   tagHi:"आधिकारिक",   tagBg:"#E1F5EE", tagColor:"#085041" },

  // Char Dham
  { id:9,  name:"Badrinath Temple",         nameHi:"बद्रीनाथ मंदिर",          location:"Chamoli, Uttarakhand",       locationHi:"चमोली, उत्तराखंड",      emoji:"❄️", color:"#E6F1FB", url:"https://badrinath-kedarnath.gov.in",           services:["Puja Booking","Abhishek","Accommodation"],          servicesHi:["पूजा बुकिंग","अभिषेक","आवास"],                           category:"Char Dham",   tag:"Govt Portal",tagHi:"सरकारी",     tagBg:"#E6F1FB", tagColor:"#1A4A8A" },
  { id:10, name:"Char Dham Yatra",          nameHi:"चार धाम यात्रा",           location:"Uttarakhand",                locationHi:"उत्तराखंड",              emoji:"🗺️", color:"#E1F5EE", url:"https://registrationandtouristcare.uk.gov.in", services:["Yatra Registration","Tourist Card","All 4 Dhams"],  servicesHi:["यात्रा पंजीकरण","टूरिस्ट कार्ड","चारों धाम"],           category:"Char Dham",   tag:"Govt Portal",tagHi:"सरकारी",     tagBg:"#E6F1FB", tagColor:"#1A4A8A" },
  { id:11, name:"Kedarnath Helicopter",     nameHi:"केदारनाथ हेलिकॉप्टर",     location:"Uttarakhand",                locationHi:"उत्तराखंड",              emoji:"🚁", color:"#FAEEDA", url:"https://www.heliyatra.irctc.co.in",            services:["Helicopter Booking","IRCTC Official"],              servicesHi:["हेलिकॉप्टर बुकिंग","IRCTC आधिकारिक"],                   category:"Char Dham",   tag:"IRCTC",      tagHi:"IRCTC",      tagBg:"#FAEEDA", tagColor:"#633806" },

  // Famous Temples
  { id:12, name:"Tirumala Venkateswara",    nameHi:"तिरुमला वेंकटेश्वर",      location:"Tirupati, Andhra Pradesh",   locationHi:"तिरुपति, आंध्र प्रदेश", emoji:"⛰️", color:"#E6F1FB", url:"https://ttdevasthanams.ap.gov.in",             services:["SSD Darshan ₹300","Accommodation","Seva Booking"], servicesHi:["SSD दर्शन ₹300","आवास","सेवा बुकिंग"],                   category:"Famous",      tag:"Official",   tagHi:"आधिकारिक",   tagBg:"#E1F5EE", tagColor:"#085041" },
  { id:13, name:"Shirdi Sai Baba",          nameHi:"शिरडी साईं बाबा",          location:"Shirdi, Maharashtra",        locationHi:"शिरडी, महाराष्ट्र",     emoji:"🌺", color:"#E1F5EE", url:"https://online.sai.org.in",                   services:["Darshan Token","Accommodation","Prasad Booking"],   servicesHi:["दर्शन टोकन","आवास","प्रसाद बुकिंग"],                    category:"Famous",      tag:"Official",   tagHi:"आधिकारिक",   tagBg:"#E1F5EE", tagColor:"#085041" },
  { id:14, name:"Vaishno Devi",             nameHi:"वैष्णो देवी",              location:"Katra, Jammu & Kashmir",     locationHi:"कटरा, जम्मू & कश्मीर", emoji:"🏔️", color:"#FAF0D7", url:"https://www.maavaishnodevi.org",               services:["Yatra Parchi","Helicopter","Room Booking"],         servicesHi:["यात्रा पर्ची","हेलिकॉप्टर","कमरा बुकिंग"],             category:"Famous",      tag:"Official",   tagHi:"आधिकारिक",   tagBg:"#E1F5EE", tagColor:"#085041" },
  { id:15, name:"Siddhivinayak Temple",     nameHi:"सिद्धिविनायक मंदिर",       location:"Mumbai, Maharashtra",        locationHi:"मुंबई, महाराष्ट्र",     emoji:"🐘", color:"#FAEEDA", url:"https://siddhivinayak.org",                   services:["Online Darshan","Prasad","Puja Booking"],           servicesHi:["ऑनलाइन दर्शन","प्रसाद","पूजा बुकिंग"],                  category:"Famous",      tag:"Official",   tagHi:"आधिकारिक",   tagBg:"#E1F5EE", tagColor:"#085041" },
  { id:16, name:"Jagannath Puri",           nameHi:"जगन्नाथ पुरी",             location:"Puri, Odisha",               locationHi:"पुरी, ओडिशा",           emoji:"🎪", color:"#FAECE7", url:"https://www.shreejagannatha.in",               services:["Seva Booking","Prasad","Rath Yatra Pass"],          servicesHi:["सेवा बुकिंग","प्रसाद","रथ यात्रा पास"],                 category:"Famous",      tag:"Official",   tagHi:"आधिकारिक",   tagBg:"#E1F5EE", tagColor:"#085041" },
  { id:17, name:"Dwarka — Dwarkadhish",     nameHi:"द्वारका — द्वारकाधीश",    location:"Dwarka, Gujarat",            locationHi:"द्वारका, गुजरात",       emoji:"🌊", color:"#E6F1FB", url:"https://dwarkadhish.org",                     services:["Darshan Timing","Aarti Schedule","Seva Booking"],  servicesHi:["दर्शन समय","आरती कार्यक्रम","सेवा बुकिंग"],            category:"Famous",      tag:"Official",   tagHi:"आधिकारिक",   tagBg:"#E1F5EE", tagColor:"#085041" },
  { id:18, name:"Amarnath Shrine",          nameHi:"अमरनाथ शिव मंदिर",         location:"Jammu & Kashmir",            locationHi:"जम्मू & कश्मीर",        emoji:"❄️", color:"#E6F1FB", url:"https://shriamarnathjishrine.com",             services:["Yatra Registration","Helicopter","Medical Cert"],   servicesHi:["यात्रा पंजीकरण","हेलिकॉप्टर","मेडिकल सर्टिफिकेट"],    category:"Famous",      tag:"Official",   tagHi:"आधिकारिक",   tagBg:"#E1F5EE", tagColor:"#085041" },
  { id:19, name:"Ram Mandir Ayodhya",       nameHi:"राम मंदिर अयोध्या",        location:"Ayodhya, Uttar Pradesh",     locationHi:"अयोध्या, उत्तर प्रदेश", emoji:"🙏", color:"#FAF0D7", url:"https://srjbtkshetra.org",                    services:["Darshan Pass","Aarti Pass","VIP Entry"],            servicesHi:["दर्शन पास","आरती पास","VIP प्रवेश"],                    category:"Famous",      tag:"Official",   tagHi:"आधिकारिक",   tagBg:"#E1F5EE", tagColor:"#085041" },
  { id:20, name:"Golden Temple",            nameHi:"स्वर्ण मंदिर",             location:"Amritsar, Punjab",           locationHi:"अमृतसर, पंजाब",         emoji:"🌟", color:"#FAF0D7", url:"https://www.sgpc.net",                        services:["Langar Seva","Kirtan Schedule","Room Booking"],     servicesHi:["लंगर सेवा","कीर्तन कार्यक्रम","कमरा बुकिंग"],          category:"Famous",      tag:"Official",   tagHi:"आधिकारिक",   tagBg:"#E1F5EE", tagColor:"#085041" },
  { id:21, name:"Meenakshi Amman Temple",   nameHi:"मीनाक्षी अम्मन मंदिर",     location:"Madurai, Tamil Nadu",        locationHi:"मदुरई, तमिल नाडु",      emoji:"🌸", color:"#FAECE7", url:"https://maduraimeenakshi.hrce.tn.gov.in",     services:["Darshan Ticket","Abhishekam","Alangaram"],          servicesHi:["दर्शन टिकट","अभिषेकम","अलंगारम"],                       category:"Famous",      tag:"Official",   tagHi:"आधिकारिक",   tagBg:"#E1F5EE", tagColor:"#085041" },
  { id:22, name:"Sabarimala Ayyappa",       nameHi:"सबरीमला अयप्पा",           location:"Pathanamthitta, Kerala",     locationHi:"पथनमथिट्टा, केरल",     emoji:"🌿", color:"#E1F5EE", url:"https://www.sabarimalatemple.org",             services:["Virtual Queue","Darshan Token","Accommodation"],    servicesHi:["वर्चुअल कतार","दर्शन टोकन","आवास"],                     category:"Famous",      tag:"Official",   tagHi:"आधिकारिक",   tagBg:"#E1F5EE", tagColor:"#085041" },
  { id:23, name:"Kamakhya Temple",          nameHi:"कामाख्या मंदिर",           location:"Guwahati, Assam",            locationHi:"गुवाहाटी, असम",         emoji:"🔱", color:"#EEEDFE", url:"https://kamakhyatemple.org",                  services:["Darshan Pass","Puja Booking","Ambubachi Info"],     servicesHi:["दर्शन पास","पूजा बुकिंग","अंबुबाची जानकारी"],           category:"Famous",      tag:"Official",   tagHi:"आधिकारिक",   tagBg:"#E1F5EE", tagColor:"#085041" },
  { id:24, name:"Kolhapur Mahalakshmi",     nameHi:"कोल्हापुर महालक्ष्मी",     location:"Kolhapur, Maharashtra",      locationHi:"कोल्हापुर, महाराष्ट्र", emoji:"👑", color:"#FAEEDA", url:"https://www.mahalaxmikolhapur.com",            services:["E-Darshan Pass","Puja Seva","Festival Booking"],    servicesHi:["E-दर्शन पास","पूजा सेवा","उत्सव बुकिंग"],               category:"Famous",      tag:"Official",   tagHi:"आधिकारिक",   tagBg:"#E1F5EE", tagColor:"#085041" },
  { id:25, name:"Tirupati Balaji (TTD App)",nameHi:"तिरुपति बालाजी ऐप",        location:"Tirupati, Andhra Pradesh",   locationHi:"तिरुपति, आंध्र प्रदेश", emoji:"📱", color:"#E6F1FB", url:"https://tirupatibalaji.ap.gov.in",             services:["Mobile Booking","e-Darshan","Prasadam Order"],      servicesHi:["मोबाइल बुकिंग","e-दर्शन","प्रसादम ऑर्डर"],             category:"Famous",      tag:"TTD App",    tagHi:"TTD ऐप",    tagBg:"#FAEEDA", tagColor:"#633806" },
];
